"""Collection-plan interactions; inserted in the dashboard's script scope."""

DASHBOARD_FEATURES = r'''
// Save state is explicit: only confirmed server writes clear the dirty flag.
let reviewDirty=false,savePromise=null,editRevision=0,confirmedReview=null,undoReviews=[],holePreviewTimer=null,holePinned=false,undoing=false;
const featureStyle=document.createElement('style');featureStyle.textContent=`
[hidden]{display:none!important}.collection-controls{padding:16px;display:grid;gap:8px}.collection-controls select,.collection-controls button{width:100%;font:inherit;padding:8px;border:1px solid #cbd5e1;border-radius:7px;background:white}.collection-controls label{font-size:12px;font-weight:650}.collection-controls small{color:#59677c}.grid-filter{width:100%;margin-top:8px;padding:7px;background:white;border:1px solid #cbd5e1;border-radius:7px}.grid-browser .panel-head{flex-wrap:wrap}.mrc-viewer-controls{opacity:1!important}.mrc-control-row .panel-note{color:#59677c!important}.viewer-controls-title{display:none!important}.review-image-viewport:fullscreen{width:100vw;height:100vh!important;background:#101827}.feature-export{width:min(540px,94vw);border:1px solid #cbd5e1;border-radius:16px;padding:24px;color:#172033}.feature-export::backdrop{background:#17203388}.feature-export label{display:block;margin-top:16px;font-weight:650}.feature-export select,.feature-export textarea{width:100%;padding:9px;border:1px solid #cbd5e1;border-radius:7px;margin-top:6px;font:inherit}.feature-export progress{width:100%;margin:12px 0}.feature-export .actions{display:flex;gap:8px;justify-content:flex-end;margin-top:16px}#export-estimate,#plan-job-status{font-size:13px;line-height:1.5;margin-top:12px}#dashboard-save-state{min-height:28px;cursor:pointer}#dashboard-save-state.error{color:#b91c1c;font-weight:700}#review-progress{font-size:12px;color:#475569}.shortcut-help{font-size:11px;line-height:1.6;color:#59677c}.target-shortlist{font-size:12px;max-height:260px;overflow:auto}.target-shortlist-row{display:flex;gap:4px;padding:5px 0;align-items:center}.target-shortlist-row button{width:auto;padding:5px}.target-shortlist-row .target-open{flex:1;text-align:left}.mrc-contrast-row{display:none!important}.mrc-active .mrc-contrast-row{display:flex!important}.grid-viewer-controls .mrc-contrast-row.disabled{display:none!important}
`;document.head.append(featureStyle);
const priorityControls=document.createElement('div');priorityControls.className='collection-controls';priorityControls.innerHTML='<label for="collection-priority">Collection priority</label><select id="collection-priority"><option value="primary">Primary</option><option value="backup">Backup</option><option value="needs_screening">Needs screening</option></select><small>Priority is separate from image rating. Mark suitable to add to the shortlist.</small><button id="pin-preferred" type="button">Pin current hole / Data image</button><button id="unpin-preview" type="button">Enable hover previews</button><button id="undo-review" type="button">Undo last saved edit</button><button id="next-unreviewed" type="button">Next unreviewed square →</button><div id="review-progress" role="status"></div><details class="shortcut-help"><summary>Keyboard shortcuts</summary>1–5: rating · S: suitable · X: unsuitable<br>← / →: hole · [ / ]: square · N: next unreviewed<br>Cmd/Ctrl + Enter: save comment & next square<br>Cmd/Ctrl + Z: undo review (outside text fields)</details><details open><summary>Collection shortlist</summary><div id="target-shortlist" class="target-shortlist"></div></details>';
document.querySelector('.review-rail').append(priorityControls);
const prioritySelect=document.getElementById('collection-priority'),saveState=document.getElementById('dashboard-save-state');saveState.setAttribute('role','status');saveState.setAttribute('aria-live','polite');
const gridFilter=document.createElement('select');gridFilter.className='grid-filter';gridFilter.setAttribute('aria-label','Filter GridSquares');gridFilter.innerHTML='<option value="all">All GridSquares</option><option value="unreviewed">Unreviewed</option><option value="suitable">Suitable</option><option value="unsuitable">Unsuitable</option><option value="missing">No screening data</option>';document.getElementById('grid-search').after(gridFilter);
function applyGridFilter(){document.querySelectorAll('#grid-list .grid-card').forEach(card=>{const g=GRIDS.find(g=>g.idx===Number(card.dataset.idx)),f=gridFilter.value;card.hidden=!(f==='all'||f==='unreviewed'&&!g.reviewed||f==='missing'&&!g.data_count||g.collection_status===f)})}
new MutationObserver(applyGridFilter).observe(document.getElementById('grid-list'),{childList:true});gridFilter.onchange=applyGridFilter;
function reviewPayload(){return selectedGridData?{idx:selectedIdx,rating:selectedGridData.rating||0,comment:document.getElementById('dashboard-comment').value,include:document.getElementById('dashboard-include').checked,collection_status:selectedGridData.collection_status||'',priority:prioritySelect.value,preferred_hole:selectedGridData.preferred_hole||''}:null}
function draftKey(idx){return 'epumap-unsaved:'+SESSION_STORAGE_KEY+':'+idx}
function storeLocalDraft(payload){try{localStorage.setItem(draftKey(payload.idx),JSON.stringify(payload))}catch(_){}}
function queueDashboardSave(){if(selectedIdx===null||!selectedGridData)return;reviewDirty=true;editRevision++;saveState.textContent='Unsaved changes…';saveState.classList.remove('error');storeLocalDraft(reviewPayload());clearTimeout(dashboardSaveTimer);dashboardSaveTimer=setTimeout(()=>{dashboardSaveTimer=null;saveDashboardReview()},450)}
async function saveDashboardReview(){
  if(savePromise)return savePromise;
  if(!reviewDirty||!selectedGridData)return true;
  const payload=reviewPayload(),revision=editRevision,previous=confirmedReview;saveState.textContent='Saving…';
  savePromise=(async()=>{try{
    const response=await fetch('/review_state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok)throw new Error(result.error||'HTTP '+response.status);
    const grid=GRIDS.find(g=>g.idx===payload.idx);if(grid)Object.assign(grid,result.review,{reviewed:true});
    if(previous&&!undoing&&JSON.stringify(previous)!==JSON.stringify(payload))undoReviews.push(previous);undoing=false;
    confirmedReview={...payload};if(revision===editRevision){reviewDirty=false;try{localStorage.removeItem(draftKey(payload.idx))}catch(_){}}
    saveState.textContent=reviewDirty?'New changes waiting to save…':'Saved';saveState.classList.remove('error');renderMarkers();renderGridList(document.getElementById('grid-search').value);updateCollectionProgress();return true;
  }catch(error){saveState.textContent='Not saved — '+error.message+' · Click here to retry';saveState.classList.add('error');reviewDirty=true;return false}finally{savePromise=null;if(reviewDirty&&revision!==editRevision){clearTimeout(dashboardSaveTimer);dashboardSaveTimer=setTimeout(()=>saveDashboardReview(),450)}}})();return savePromise;
}
async function flushDashboardReview(){clearTimeout(dashboardSaveTimer);dashboardSaveTimer=null;if(savePromise&&!await savePromise)return false;while(reviewDirty){if(!await saveDashboardReview())return false}return true}
saveState.onclick=()=>flushDashboardReview();window.addEventListener('beforeunload',event=>{if(reviewDirty||savePromise){event.preventDefault();event.returnValue=''}});
function loadReviewFields(value){setDashboardRating(value.rating||0,false);setDashboardCollectionStatus(value.collection_status||'',false);document.getElementById('dashboard-comment').value=value.comment||'';document.getElementById('dashboard-include').checked=value.include!==false;prioritySelect.value=value.priority||'primary';selectedGridData.preferred_hole=value.preferred_hole||''}
function onGridLoaded(data){cancelHolePreview();holePinned=false;undoReviews=[];prioritySelect.value=data.priority||'primary';confirmedReview=reviewPayload();reviewDirty=false;saveState.title='Review changes are saved automatically. Click to retry a failed save.';let draft;try{draft=JSON.parse(localStorage.getItem(draftKey(data.idx))||'null')}catch(_){}if(draft){loadReviewFields(draft);reviewDirty=true;editRevision++;saveState.textContent='Recovered unsaved edits — click here to save';saveState.classList.add('error')}if(data.preferred_hole){const i=dashboardHoles.findIndex(h=>h.data_name===data.preferred_hole||h.foil_id===data.preferred_hole);if(i>=0){showDashboardHoleByIndex(i);holePinned=true}}updateCollectionProgress();document.getElementById('selected-grid-mrc').title=data.grid_has_mrc?'Load the MRC with the same acquisition filename as this preview':'No exact matching MRC for '+data.name+'; another acquisition will not be substituted'}
prioritySelect.onchange=()=>{if(selectedGridData){selectedGridData.priority=prioritySelect.value;queueDashboardSave()}};
function cancelHolePreview(){clearTimeout(holePreviewTimer);holePreviewTimer=null}
function previewHole(index){cancelHolePreview();if(!holePinned)holePreviewTimer=setTimeout(()=>showDashboardHoleByIndex(index),220)}
function pinHole(index){cancelHolePreview();showDashboardHoleByIndex(index);holePinned=true;if(selectedGridData&&activeHole){selectedGridData.preferred_hole=activeHole.data_name||activeHole.foil_id;queueDashboardSave()}}
document.getElementById('pin-preferred').onclick=()=>pinHole(activeHoleIndex);
document.getElementById('unpin-preview').onclick=()=>{holePinned=false;cancelHolePreview();saveState.textContent='Hover previews enabled; preferred report image remains saved'};
document.getElementById('undo-review').onclick=()=>undoReview();
async function undoReview(){if(!await flushDashboardReview())return;const previous=undoReviews.pop();if(!previous)return;loadReviewFields(previous);undoing=true;queueDashboardSave();await flushDashboardReview()}
async function nextUnreviewed(){const next=[...GRIDS.filter(g=>g.idx>(selectedIdx??-1)),...GRIDS.filter(g=>g.idx<=(selectedIdx??-1))].find(g=>!g.reviewed);if(next)await selectGrid(next.idx,false);else saveState.textContent='All GridSquares reviewed. Your collection plan is ready to export.'}
document.getElementById('next-unreviewed').onclick=nextUnreviewed;
function updateCollectionProgress(){const reviewed=GRIDS.filter(g=>g.reviewed).length,targets=GRIDS.filter(g=>g.collection_status==='suitable'&&g.include!==false);document.getElementById('review-progress').textContent=reviewed+' / '+GRIDS.length+' reviewed · '+targets.length+' screened collection targets';const stat=document.querySelectorAll('.stat-value')[1];if(stat)stat.textContent=reviewed;document.getElementById('undo-review').disabled=!undoReviews.length;const list=document.getElementById('target-shortlist');list.replaceChildren();targets.sort((a,b)=>({primary:0,backup:1,needs_screening:2}[a.priority]||0)-({primary:0,backup:1,needs_screening:2}[b.priority]||0)||(a.target_order??a.idx)-(b.target_order??b.idx));targets.forEach((g,index)=>{const row=document.createElement('div');row.className='target-shortlist-row';const open=document.createElement('button');open.className='target-open';open.textContent=(g.idx+1)+' · '+g.id+' · '+(g.priority||'primary');open.onclick=()=>selectGrid(g.idx,false);row.append(open);for(const [direction,label] of [[-1,'↑'],[1,'↓']]){const b=document.createElement('button');b.textContent=label;b.title='Move target '+(direction<0?'earlier':'later');b.disabled=!targets[index+direction]||targets[index+direction].priority!==g.priority;b.onclick=async()=>{if(!await flushDashboardReview())return;const order=targets.map(x=>x.idx);[order[index],order[index+direction]]=[order[index+direction],order[index]];try{const r=await fetch('/target_order',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({order})});if(!r.ok)throw new Error('Could not save order');order.forEach((idx,i)=>GRIDS.find(x=>x.idx===idx).target_order=i);updateCollectionProgress()}catch(e){saveState.textContent=e.message}};row.append(b)}list.append(row)});const manual=UNSCREENED.filter(t=>t.selected);if(manual.length){const note=document.createElement('p');note.textContent=manual.length+' manual Atlas targets · Needs screening';list.append(note)}}
document.addEventListener('keydown',event=>{if(event.target.closest('input,textarea,select')||event.altKey||document.querySelector('dialog[open]'))return;if((event.metaKey||event.ctrlKey)&&event.key==='z'){event.preventDefault();undoReview();return}if(event.metaKey||event.ctrlKey)return;const key=event.key.toLowerCase();if(/^[1-5]$/.test(key)){event.preventDefault();setDashboardRating(Number(key))}else if(key==='s')setDashboardCollectionStatus('suitable');else if(key==='x')setDashboardCollectionStatus('unsuitable');else if(key==='n')nextUnreviewed();else if(key==='arrowleft'||key==='arrowright'){event.preventDefault();cancelHolePreview();showDashboardHoleByIndex(activeHoleIndex+(key==='arrowleft'?-1:1))}else if(key==='['||key===']'){const idx=(selectedIdx??0)+(key==='['?-1:1);if(idx>=0&&idx<GRIDS.length)selectGrid(idx,false)}});
// All image tools stay below the image. Fullscreen retains the same pan/zoom stage.
function installEnlarge(view,host,label){
  if(!view||!host)return;
  const button=document.createElement('button');button.type='button';button.className='button viewer-enlarge';button.textContent='Enlarge';button.setAttribute('aria-label','Enlarge '+label);host.append(button);
  const close=document.createElement('button');close.type='button';close.className='button viewer-shrink';close.textContent='Close enlarged view · Esc';close.setAttribute('aria-label','Close enlarged '+label);view.append(close);
  let previousOverflow='';
  function fallback(){previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';view.classList.add('viewer-expanded');close.focus()}
  function restore(){if(view.classList.contains('viewer-expanded')){view.classList.remove('viewer-expanded');document.body.style.overflow=previousOverflow;button.focus()}}
  button.onclick=async()=>{if(view.classList.contains('viewer-expanded')||document.fullscreenElement===view)return;try{if(view.requestFullscreen){await view.requestFullscreen();close.focus()}else fallback()}catch(_){fallback()}};
  close.onclick=()=>{if(document.fullscreenElement===view)document.exitFullscreen().catch(()=>{});else restore()};
  document.addEventListener('keydown',event=>{if(event.key==='Escape'&&view.classList.contains('viewer-expanded')){event.preventDefault();restore()}});
  document.addEventListener('fullscreenchange',()=>{if(!document.fullscreenElement&&document.activeElement===close)button.focus()});
  if(view.id==='atlas-viewport'){
    const img=view.querySelector('#atlas-image');
    function fitAtlas(){if(!img)return;if(document.fullscreenElement===view||view.classList.contains('viewer-expanded')){const ratio=Math.min(view.clientWidth/(img.naturalWidth||1),view.clientHeight/(img.naturalHeight||1));img.style.width=(img.naturalWidth||1)*ratio+'px';img.style.height=(img.naturalHeight||1)*ratio+'px'}else{img.style.removeProperty('width');img.style.removeProperty('height')}}
    new ResizeObserver(fitAtlas).observe(view);img?.addEventListener('load',fitAtlas);document.addEventListener('fullscreenchange',fitAtlas);
  }
}
document.querySelectorAll('.review-image-viewport').forEach(view=>installEnlarge(view,view.closest('.selected-media-card,.linked-image-panel')?.querySelector('.mrc-control-row:not(.mrc-contrast-row)'),view.querySelector('img')?.id==='selected-overlay-image'?'GridSquare':view.querySelector('img')?.id==='comparison-data'?'Data image':'FoilHole'));
if(HAS_ATLAS){const enlargeHost=document.createElement('div');enlargeHost.className='atlas-enlarge-controls';atlasViewport.after(enlargeHost);installEnlarge(atlasViewport,enlargeHost,'Atlas')}
const enlargeStyle=document.createElement('style');enlargeStyle.textContent='.viewer-shrink{display:none!important;position:absolute;right:14px;top:14px;z-index:30;cursor:pointer}.review-image-viewport:fullscreen .viewer-shrink,.atlas-viewport:fullscreen .viewer-shrink,.viewer-expanded .viewer-shrink{display:block!important}.atlas-viewport:fullscreen,.review-image-viewport:fullscreen,.viewer-expanded{width:100vw!important;height:100vh!important;max-height:none!important;background:#101827}.viewer-expanded{position:fixed!important;inset:0!important;z-index:1000!important;border-radius:0!important}.atlas-viewport:fullscreen .atlas-image,.atlas-viewport.viewer-expanded .atlas-image{max-height:100vh!important}.atlas-enlarge-controls{padding:8px 12px 0}.viewer-enlarge{white-space:nowrap}';document.head.append(enlargeStyle);
document.querySelectorAll('.mrc-viewer-controls').forEach(controls=>{const auto=document.createElement('button');auto.className='button';auto.textContent='Auto contrast';auto.onclick=()=>{const low=controls.querySelector('.mrc-low'),high=controls.querySelector('.mrc-high');low.value=2;high.value=98;low.dispatchEvent(new Event('input'))};controls.querySelector('.mrc-contrast-row')?.append(auto)});
const atlasLayer=document.createElement('select');atlasLayer.setAttribute('aria-label','Atlas marker colors');atlasLayer.className='button';atlasLayer.innerHTML='<option value="status">Collection status colors</option><option value="rating">Rating colors</option>';atlasViewport?.closest('.panel')?.querySelector('.panel-head')?.append(atlasLayer);
function recolorAtlas(){if(atlasLayer.value==='rating')return;document.querySelectorAll('.grid-marker').forEach(marker=>{const g=GRIDS.find(x=>x.idx===Number(marker.dataset.idx));if(g)marker.style.background=g.collection_status==='suitable'?'#059669':g.collection_status==='unsuitable'?'#dc2626':'#64748b'})}if(markerLayer)new MutationObserver(recolorAtlas).observe(markerLayer,{childList:true});atlasLayer.onchange=()=>{renderMarkers();recolorAtlas()};
// Identical, non-destructive image tools for PNG and MRC previews.
function installImageAdjustments(img,host,kind,getSource,isMrc,restore){
  const panel=document.createElement('details');panel.className='image-adjustments';panel.innerHTML='<summary>Adjust image <span class="adjustment-badge">Original preview</span></summary><div class="adjustment-presets"><button type="button" data-preset="robust">Auto · robust</button><button type="button" data-preset="strong">Auto · strong</button><button type="button" data-preset="full">Full range</button><button type="button" data-preset="equalize">Equalize histogram</button><button type="button" data-preset="reset">Reset image</button></div><div class="adjustment-fields"><label>Black percentile <input aria-label="Black percentile" class="adjust-black" type="number" min="0" max="99.9" step="0.1" value="1"></label><label>White percentile <input aria-label="White percentile" class="adjust-white" type="number" min="0.1" max="100" step="0.1" value="99"></label><label>Gamma <output class="gamma-value">1.00</output><input aria-label="Gamma" class="adjust-gamma" type="range" min="0.2" max="3" step="0.05" value="1"></label><label>Low-pass σ <output class="sigma-value">Off</output><input aria-label="Low-pass filter sigma" class="adjust-sigma" type="range" min="0" max="4" step="0.1" value="0"></label></div><div class="adjustment-note">Display only; original files and exports stay unchanged. Low-pass σ is in preview pixels (maximum 2048 px image). Filtering can conceal fine detail.</div><div class="adjustment-status" role="status"></div>';
  host.append(panel);const black=panel.querySelector('.adjust-black'),white=panel.querySelector('.adjust-white'),gamma=panel.querySelector('.adjust-gamma'),sigma=panel.querySelector('.adjust-sigma'),badge=panel.querySelector('.adjustment-badge'),status=panel.querySelector('.adjustment-status');let enabled=false,mode='percentile',timer=null;
  function values(){panel.querySelector('.gamma-value').textContent=Number(gamma.value).toFixed(2);panel.querySelector('.sigma-value').textContent=Number(sigma.value)?Number(sigma.value).toFixed(1)+' px':'Off'}
  function render(){clearTimeout(timer);if(!enabled)return false;const source=getSource();if(!source||!source.png){status.textContent='Select an image first (for Atlas, switch from EPU categories to Screened, PNG, or MRC).';return false}const lo=Number(black.value),hi=Number(white.value);if(black.value===''||white.value===''||!(lo>=0&&hi<=100&&lo<hi)){status.textContent='Black percentile must be less than white percentile, between 0 and 100.';return true}let sourceKind=kind;if(kind==='grid'&&!isMrc()&&source.png)sourceKind=new URL(source.png,location.href).searchParams.get('kind')||'grid';const params=new URLSearchParams({idx:String(selectedIdx??-1),kind:sourceKind,name:source.name||'',mrc:String(isMrc()),low:String(lo),high:String(hi),gamma:gamma.value,sigma:sigma.value,mode});status.textContent='Updating preview…';badge.textContent=(mode==='equalize'?'Histogram equalization':lo+'–'+hi+'%')+' · γ '+Number(gamma.value).toFixed(2)+(Number(sigma.value)?' · Low-pass σ '+sigma.value+' px':'');img.src='/adjusted_preview?'+params;return true}
  function queue(manual=false){enabled=true;if(manual)mode='percentile';values();clearTimeout(timer);timer=setTimeout(render,250)}
  black.oninput=white.oninput=()=>queue(true);gamma.oninput=sigma.oninput=()=>queue();
  panel.querySelectorAll('[data-preset]').forEach(button=>button.onclick=()=>{clearTimeout(timer);const preset=button.dataset.preset;if(preset==='reset'){enabled=false;mode='percentile';black.value=1;white.value=99;gamma.value=1;sigma.value=0;values();badge.textContent='Original preview';status.textContent='';restore();return}enabled=true;mode=preset==='equalize'?'equalize':'percentile';black.value=preset==='strong'?2:preset==='full'?0:1;white.value=preset==='strong'?98:preset==='full'?100:99;gamma.value=1;values();render()});
  img.addEventListener('load',()=>{if(img.getAttribute('src')?.startsWith('/adjusted_preview?'))status.textContent='Preview adjusted; original unchanged.'});img.addEventListener('error',()=>{if(enabled)status.textContent='Preview adjustment failed. Try Reset image or reconnect to the server.'});img._applyAdjustments=render;
}
const adjustmentStyle=document.createElement('style');adjustmentStyle.textContent=`
.image-adjustments{border-top:1px solid #e2e8f0;margin-top:8px;padding:9px 2px;color:#334155;font-size:12px}.image-adjustments summary{cursor:pointer;font-weight:650}.adjustment-badge{font-weight:400;font-size:11px;color:#64748b;margin-left:8px}.adjustment-presets{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.adjustment-presets button{padding:6px 9px;border:1px solid #cbd5e1;border-radius:6px;background:white;color:#334155;font-size:11px;cursor:pointer}.adjustment-fields{display:grid;grid-template-columns:1fr 1fr;gap:10px}.adjustment-fields label{display:block;font-size:11px}.adjustment-fields input{display:block;width:100%;margin-top:5px}.adjustment-fields input[type=number]{border:1px solid #cbd5e1;border-radius:5px;padding:5px;color:#334155}.adjustment-note,.adjustment-status{font-size:10px;line-height:1.5;margin-top:8px;color:#64748b}.atlas-adjustments{padding:0 12px 8px}.mrc-viewer-controls .mrc-contrast-row,.mrc-viewer-controls.mrc-active .mrc-contrast-row,.atlas-mrc-contrast{display:none!important}.dashboard-hole-hit.active,.dashboard-hole-hit.active:not(:hover):not(:focus-visible){border:3px solid #67e8f9!important;background:transparent!important;box-shadow:0 0 0 2px #0f172a,0 0 0 5px rgba(103,232,249,.65)!important;z-index:4}.dashboard-hole-hit.active::after{content:'Viewing';position:absolute;left:50%;top:calc(100% + 8px);transform:translateX(-50%);background:#0f172a;color:#a5f3fc;font:600 10px/1.4 system-ui;padding:2px 5px;border-radius:4px;pointer-events:none}
`;document.head.append(adjustmentStyle);
if(HAS_ATLAS){const atlasAdjustHost=document.createElement('div');atlasAdjustHost.className='atlas-adjustments';atlasViewport.after(atlasAdjustHost);const atlasImg=document.getElementById('atlas-image');installImageAdjustments(atlasImg,atlasAdjustHost,'atlas_overview',()=>atlasMode==='categories'?null:{png:'/atlas_overview_raw',name:''},()=>atlasMode==='mrc',()=>{if(atlasMode==='mrc')loadAtlasMrc();else atlasImg.src=(atlasMode==='categories'?'/atlas_overview_categories':'/atlas_overview_raw')+'?session='+encodeURIComponent(CACHE_KEY)});document.querySelectorAll('.atlas-mode').forEach(button=>{const original=button.onclick;button.onclick=event=>{original(event);atlasImg._applyAdjustments()}})}
// A single export entry point; HTML/PDF jobs use confirmed server snapshots.
const exportDialog=document.createElement('dialog');exportDialog.className='feature-export';exportDialog.innerHTML='<h2>Export collection plan</h2><p>Portable results for the microscope or a colleague. HTML opens in any modern browser without EPU Mapper.</p><label for="plan-format">Format</label><select id="plan-format"><option value="html">Interactive HTML · compact JPEGs, no MRCs</option><option value="full">PDF · printable collection sheet</option></select><label for="plan-scope">Screening images</label><select id="plan-scope"><option value="targets">All included collection targets</option><option value="representative">One highest-rated suitable square</option><option value="all_screened">All screening images · every exposure</option></select><label for="plan-summary">Collection instructions / session summary</label><textarea id="plan-summary" rows="3" maxlength="4000"></textarea><div id="export-estimate"></div><progress id="plan-progress" hidden></progress><div id="plan-job-status" role="status"></div><div class="actions"><button class="button" id="plan-close">Close</button><button class="button primary" id="plan-export">Export</button></div>';document.body.append(exportDialog);
const topActions=document.querySelector('.top-actions');topActions.querySelectorAll('a').forEach(a=>a.remove());const oldPortable=document.getElementById('portable-export-dashboard');oldPortable.hidden=false;oldPortable.textContent='Export full session';oldPortable.title='Copy all original data and annotations; no HTML rendering';const exportButton=document.createElement('button');exportButton.className='button primary';exportButton.textContent='Export collection plan';topActions.append(exportButton);let planPollTimer=null;
async function exportEstimate(){const format=document.getElementById('plan-format').value,scope=document.getElementById('plan-scope');try{const r=await fetch('/export_preview?scope='+scope.value);const data=await r.json();document.getElementById('export-estimate').textContent=data.grids+' squares with screening details · '+data.images+' source previews · '+data.source_mb+' MB of source images. HTML embeds compressed JPEG previews only, never MRCs; final size may differ. All annotations and manual targets are included.'}catch(_){document.getElementById('export-estimate').textContent='Preview unavailable; reconnect before exporting.'}}
exportButton.onclick=async()=>{if(!await flushDashboardReview())return;exportDialog.showModal();document.getElementById('plan-job-status').textContent='';try{const r=await fetch('/summary');document.getElementById('plan-summary').value=(await r.json()).summary||''}catch(_){}exportEstimate()};document.getElementById('plan-close').onclick=()=>exportDialog.close();document.getElementById('plan-format').onchange=document.getElementById('plan-scope').onchange=exportEstimate;
async function pollPlan(jobId){try{const response=await fetch('/report_jobs/'+encodeURIComponent(jobId)),job=await response.json();if(!response.ok)throw new Error(job.error||'Could not read progress');document.getElementById('plan-job-status').textContent=job.message;if(job.status==='done'){document.getElementById('plan-progress').hidden=true;const a=document.createElement('a');a.className='button primary';a.textContent='Download '+(job.kind==='html'?'HTML plan':'PDF report');a.href=job.download_url;document.getElementById('plan-job-status').append(document.createElement('br'),a);document.getElementById('plan-export').disabled=false}else if(job.status==='error')throw new Error(job.message);else planPollTimer=setTimeout(()=>pollPlan(jobId),750)}catch(error){document.getElementById('plan-job-status').textContent=error.message;document.getElementById('plan-progress').hidden=true;document.getElementById('plan-export').disabled=false}}
document.getElementById('plan-export').onclick=async()=>{const button=document.getElementById('plan-export');button.disabled=true;try{if(!await flushDashboardReview())throw new Error('Save the current review before exporting.');const summaryResponse=await fetch('/summary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({summary:document.getElementById('plan-summary').value})});if(!summaryResponse.ok)throw new Error('Session summary could not be saved.');const kind=document.getElementById('plan-format').value;const response=await fetch('/report_jobs',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,scope:document.getElementById('plan-scope').value})}),result=await response.json();if(!response.ok)throw new Error(result.error||'Could not start export');document.getElementById('plan-progress').hidden=false;document.getElementById('plan-job-status').textContent='Rendering confirmed review snapshot…';pollPlan(result.job_id)}catch(error){document.getElementById('plan-job-status').textContent=error.message;button.disabled=false}};
function alignViewerHeaders(){const a=atlasViewport?.closest('.panel')?.querySelector('.panel-head'),b=document.querySelector('#selected-detail > .panel-head');if(!a||!b)return;for(const head of [a,b]){head.style.setProperty('height','auto','important');head.style.setProperty('min-height','0','important')}const height=Math.ceil(Math.max(a.scrollHeight,b.scrollHeight))+8;for(const head of [a,b])head.style.setProperty('height',height+'px','important')}
window.addEventListener('resize',alignViewerHeaders);alignViewerHeaders();
updateCollectionProgress();recolorAtlas();if(GRIDS.length)selectGrid(GRIDS.find(g=>!g.reviewed)?.idx??GRIDS[0].idx,false);
'''
